// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Recommends treatments, including dosage, for plant diseases.
 *
 * - recommendTreatment - A function that recommends treatments for plant diseases.
 * - RecommendTreatmentInput - The input type for the recommendTreatment function.
 * - RecommendTreatmentOutput - The return type for the recommendTreatment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendTreatmentInputSchema = z.object({
  diseaseName: z.string().describe('The name of the detected plant disease.'),
  plantSpecies: z.string().describe('The species of the affected plant.'),
});

export type RecommendTreatmentInput = z.infer<typeof RecommendTreatmentInputSchema>;

const RecommendTreatmentOutputSchema = z.object({
  treatment: z.string().describe('Recommended treatment for the disease.'),
  dosage: z.string().describe('Recommended dosage for the treatment, specific to the plant species.'),
});

export type RecommendTreatmentOutput = z.infer<typeof RecommendTreatmentOutputSchema>;

export async function recommendTreatment(input: RecommendTreatmentInput): Promise<RecommendTreatmentOutput> {
  return recommendTreatmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendTreatmentPrompt',
  input: {schema: RecommendTreatmentInputSchema},
  output: {schema: RecommendTreatmentOutputSchema},
  prompt: `You are an expert in plant health, specializing in treatment recommendations and dosages.

  Based on the identified disease and plant species, provide a treatment recommendation and a specific dosage.

  Disease: {{{diseaseName}}}
  Plant Species: {{{plantSpecies}}}
  
  Ensure that the dosage is safe and effective for the given plant species. Include units and frequency.
  If no dosage can be confidently determined, note that the dosage should be determined by a professional.`, //Clarified prompt
});

const recommendTreatmentFlow = ai.defineFlow(
  {
    name: 'recommendTreatmentFlow',
    inputSchema: RecommendTreatmentInputSchema,
    outputSchema: RecommendTreatmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
